### PR TITLE
added website layout

### PR DESCRIPTION
**Pull request by Sarveshk76**
#6

### CODE REVIEW

**Comment by mrigaankzoro** [comment]
Join the grp  [[](https://chat.whatsapp.com/C9BzQpWPOqbJUj51N8cWr8)](url)

**Comment by mrigaankzoro** [comment]
Join grp [[](https://chat.whatsapp.com/C9BzQpWPOqbJUj51N8cWr8)](url)

**Comment by mrigaankzoro** [comment]
Join gro[https://chat.whatsapp.com/C9BzQpWPOqbJUj51N8cWr8](url)

**Comment by Sarveshk76** [comment]
URL is not working

**Comment by Sarveshk76** [comment]
url is not working

**Comment by mrigaankzoro** [comment]
https://chat.whatsapp.com/C9BzQpWPOqbJUj51N8cWr8

**Pull request merged**
